function p10ValidateItinerary_(input,rows,ss){const o=p10ValidateExistingId_(input.id,rows,/^I\d{3,}$/,'行程');o.date=p10RequiredDate_(input.date,'日期');o.start_time=p10OptionalTime_(input.start_time,'開始時間');o.end_time=p10OptionalTime_(input.end_time,'結束時間');o.group=p10EnumValue_(input.group,P10_CONFIG.GROUPS,'group');o.city=p10Text_(input.city,100);o.title=p10RequiredText_(input.title,'標題',120);o.description=p10Text_(input.description,1000);o.place_id=p10OptionalForeignId_(ss,'places',input.place_id,'place_id');o.transport_id=p10OptionalForeignId_(ss,'transport',input.transport_id,'transport_id');o.reservation_id=p10OptionalForeignId_(ss,'reservations',input.reservation_id,'reservation_id');o.certainty=p10EnumValue_(input.certainty,P10_CONFIG.CERTAINTIES,'certainty');if(input.id){const existing=rows.find(function(r){return r.id===input.id;});o.order=existing?Number(existing.order||10):10;}o.notes=p10Text_(input.notes,1000);return o;}
function p10ValidateReservation_(input,rows,ss){const o=p10ValidateExistingId_(input.id,rows,/^R\d{3,}$/,'預訂');o.category=p10EnumValue_(input.category,P10_CONFIG.RESERVATION_CATEGORIES,'category');o.name=p10RequiredText_(input.name,'名稱',160);o.date=p10OptionalDate_(input.date,'日期');o.time=p10OptionalTime_(input.time,'時間');o.group=p10EnumValue_(input.group,P10_CONFIG.GROUPS,'group');o.status=p10EnumValue_(input.status,P10_CONFIG.RESERVATION_STATUSES,'status');o.owner_member_id=p10OptionalForeignId_(ss,'members',input.owner_member_id,'owner_member_id');o.booking_url=p10OptionalHttpsUrl_(input.booking_url,'booking_url');o.deadline=p10OptionalDate_(input.deadline,'deadline');o.price=p10OptionalNumber_(input.price,'price');o.currency=p10Text_(input.currency,8).toUpperCase();o.confirmation_no=p10Text_(input.confirmation_no,120);o.notes=p10Text_(input.notes,1000);return o;}
function p10ValidateHotel_(input,rows,ss){const o=p10ValidateExistingId_(input.id,rows,/^H\d{3,}$/,'住宿');o.city=p10RequiredText_(input.city,'城市',100);o.hotel_name=p10RequiredText_(input.hotel_name,'住宿名稱',160);o.check_in=p10RequiredDate_(input.check_in,'入住日期');o.check_out=p10RequiredDate_(input.check_out,'退房日期');if(o.check_out<=o.check_in)throw new Error('退房日期必須晚於入住日期');o.group=p10EnumValue_(input.group,P10_CONFIG.GROUPS,'group');o.address=p10Text_(input.address,300);o.place_id=p10OptionalForeignId_(ss,'places',input.place_id,'place_id');o.google_maps_url=p10OptionalHttpsUrl_(input.google_maps_url,'google_maps_url');o.booking_url=p10OptionalHttpsUrl_(input.booking_url,'booking_url');o.reservation_id=p10OptionalForeignId_(ss,'reservations',input.reservation_id,'reservation_id');o.confirmation_no=p10Text_(input.confirmation_no,120);o.notes=p10Text_(input.notes,1000);return o;}
function p10ValidateFlight_(input,rows,ss){const o=p10ValidateExistingId_(input.id,rows,/^F\d{3,}$/,'航班');o.date=p10RequiredDate_(input.date,'日期');o.airline=p10RequiredText_(input.airline,'航空公司',120);o.flight_no=p10RequiredText_(input.flight_no,'航班號',40);o.departure_airport=p10RequiredText_(input.departure_airport,'出發機場',80);o.arrival_airport=p10RequiredText_(input.arrival_airport,'抵達機場',80);o.departure_time=p10OptionalTime_(input.departure_time,'起飛時間');o.arrival_time=p10OptionalTime_(input.arrival_time,'抵達時間');o.group=p10EnumValue_(input.group,P10_CONFIG.GROUPS,'group');o.reservation_id=p10OptionalForeignId_(ss,'reservations',input.reservation_id,'reservation_id');o.booking_reference=p10Text_(input.booking_reference,120);o.notes=p10Text_(input.notes,1000);return o;}
function p10ValidateTransport_(input,rows,ss){const o=p10ValidateExistingId_(input.id,rows,/^T\d{3,}$/,'交通');o.date=p10RequiredDate_(input.date,'日期');o.type=p10EnumValue_(input.type,P10_CONFIG.TRANSPORT_TYPES,'type');o.from_place_id=p10RequiredForeignId_(ss,'places',input.from_place_id,'出發地');o.to_place_id=p10RequiredForeignId_(ss,'places',input.to_place_id,'目的地');if(o.from_place_id===o.to_place_id)throw new Error('出發地與目的地不可相同');o.departure_time=p10OptionalTime_(input.departure_time,'出發時間');o.arrival_time=p10OptionalTime_(input.arrival_time,'抵達時間');o.operator=p10Text_(input.operator,120);o.service_no=p10Text_(input.service_no,80);o.group=p10EnumValue_(input.group,P10_CONFIG.GROUPS,'group');o.reservation_required=p10BooleanValue_(input.reservation_required,'reservation_required');o.reservation_id=p10OptionalForeignId_(ss,'reservations',input.reservation_id,'reservation_id');o.url=p10OptionalHttpsUrl_(input.url,'url');o.notes=p10Text_(input.notes,1000);return o;}
function p10ValidatePlace_(input,rows,ss){const o=p10ValidateExistingId_(input.id,rows,/^P\d{3,}$/,'地點');o.name=p10RequiredText_(input.name,'地點名稱',160);o.city=p10Text_(input.city,100);o.category=p10Text_(input.category,80);o.address=p10Text_(input.address,300);o.opening_hours=p10Text_(input.opening_hours,500);o.website=p10OptionalHttpsUrl_(input.website,'website');o.notes=p10Text_(input.notes,1000);const existing=input.id?rows.find(function(r){return r.id===input.id;}):null;const sameLocation=!!existing&&String(existing.name||'').trim()===o.name&&String(existing.city||'').trim()===o.city&&String(existing.address||'').trim()===o.address;if(sameLocation&&p10HasCoordinatePair_(existing.latitude,existing.longitude)){o.latitude=Number(existing.latitude);o.longitude=Number(existing.longitude);o.google_maps_url=String(existing.google_maps_url||p10MapsUrlForCoordinates_(o.latitude,o.longitude));return o;}const located=p10GeocodePlace_(o.name,o.city,o.address);if(located){o.latitude=located.latitude;o.longitude=located.longitude;if(!o.address&&located.formatted_address)o.address=p10Text_(located.formatted_address,300);o.google_maps_url=p10MapsUrlForCoordinates_(o.latitude,o.longitude);}else{o.latitude='';o.longitude='';o.google_maps_url='';}return o;}
function p10GeocodePlace_(name,city,address){const query=String(address||'').trim()||[String(name||'').trim(),String(city||'').trim(),'Japan'].filter(Boolean).join(', ');if(!query)return null;try{const response=Maps.newGeocoder().setRegion('jp').setLanguage('ja').geocode(query);if(!response||!response.results||!response.results.length)return null;const result=response.results[0],loc=result&&result.geometry&&result.geometry.location;if(!loc||!Number.isFinite(Number(loc.lat))||!Number.isFinite(Number(loc.lng)))return null;return{latitude:Number(loc.lat),longitude:Number(loc.lng),formatted_address:result.formatted_address||''};}catch(err){console.warn('P10 place geocode failed: '+query+' / '+err);return null;}}
function p10MapsUrlForCoordinates_(lat,lng){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(String(lat)+','+String(lng));}
function p10HasCoordinatePair_(lat,lng){return lat!==null&&lat!==undefined&&String(lat).trim()!==''&&lng!==null&&lng!==undefined&&String(lng).trim()!==''&&Number.isFinite(Number(lat))&&Number.isFinite(Number(lng));}
function p10PlaceLocationResult_(row){return{located:p10HasCoordinatePair_(row.latitude,row.longitude),latitude:row.latitude||'',longitude:row.longitude||'',address:row.address||'',google_maps_url:row.google_maps_url||''};}
function p10AssertNotReferenced_(ss,id,refs){refs.forEach(function(ref){const rows=p10ReadSheetObjects_(p10RequiredSheet_(ss,P10_CONFIG.SHEETS[ref.sheet]));if(rows.some(function(r){return r[ref.field]===id;}))throw p10Error_('CONFLICT','此資料仍被 '+ref.label+' 引用，請先解除 '+ref.field+' 關聯');});}
function p10RequiredForeignId_(ss,key,value,label){const v=String(value||'').trim();if(!v)throw new Error(label+'不可空白');return p10ExistingForeignId_(ss,key,v,label);}
function p10OptionalForeignId_(ss,key,value,label){const v=String(value||'').trim();return v?p10ExistingForeignId_(ss,key,v,label):'';}
function p10ExistingForeignId_(ss,key,v,label){const exists=p10ReadSheetObjects_(p10RequiredSheet_(ss,P10_CONFIG.SHEETS[key])).some(function(r){return r.id===v;});if(!exists)throw p10Error_('NOT_FOUND',label+' 不存在');return v;}
function p10ValidateExistingId_(idValue,rows,pattern,label){const o={},id=String(idValue||'').trim();if(!id)return o;if(!pattern.test(id))throw new Error(label+' id 格式錯誤');if(!rows.some(function(r){return r.id===id;}))throw p10Error_('NOT_FOUND','找不到要修改的'+label);o.id=id;return o;}
function p10ReadTable_(sheet){const headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0],rows=sheet.getLastRow()>1?sheet.getRange(2,1,sheet.getLastRow()-1,headers.length).getDisplayValues():[];return{headers:headers,objects:rows.filter(function(r){return r.some(function(v){return String(v).trim()!=='';});}).map(function(r){return p10ObjectFromRow_(headers,r);})};}
function p10ReadSheetObjects_(sheet){return p10ReadTable_(sheet).objects;}
function p10ObjectFromRow_(headers,row){const o={};headers.forEach(function(h,i){o[h]=row[i]===''?null:row[i];});return o;}
function p10WriteObjectRow_(sheet,rowIndex,headers,obj){sheet.getRange(rowIndex,1,1,headers.length).setValues([headers.map(function(h){return p10ValueForSheet_(obj[h]);})]);}
function p10AppendObjectRow_(sheet,headers,obj){const lastRow=sheet.getLastRow(),newRow=lastRow+1;if(newRow>sheet.getMaxRows())sheet.insertRowsAfter(sheet.getMaxRows(),1);if(lastRow>=2){const source=sheet.getRange(lastRow,1,1,headers.length),target=sheet.getRange(newRow,1,1,headers.length);source.copyTo(target,SpreadsheetApp.CopyPasteType.PASTE_FORMAT,false);source.copyTo(target,SpreadsheetApp.CopyPasteType.PASTE_DATA_VALIDATION,false);}sheet.getRange(newRow,1,1,headers.length).setValues([headers.map(function(h){return p10ValueForSheet_(obj[h]);})]);}
function p10DeleteById_(sheet,id){const t=p10ReadTable_(sheet),i=t.objects.findIndex(function(r){return r.id===id;});if(i<0)throw p10Error_('NOT_FOUND','找不到指定資料');sheet.deleteRow(i+2);}
function p10RequiredSheet_(ss,name){const sh=ss.getSheetByName(name);if(!sh)throw p10Error_('INTERNAL_ERROR','找不到 '+name+' 工作表');return sh;}
function p10WithWriteLock_(fn){const lock=LockService.getScriptLock();lock.waitLock(10000);try{return fn();}finally{lock.releaseLock();}}
function p10NextId_(ids,prefix,width){const max=ids.reduce(function(m,id){const x=String(id||'').match(new RegExp('^'+prefix+'(\\d+)$'));return x?Math.max(m,Number(x[1])):m;},0);return prefix+String(max+1).padStart(width,'0');}
function p10NextItineraryOrder_(date,rows){const orders=rows.filter(function(r){return r.date===date;}).map(function(r){return Number(r.order||0);}).filter(function(n){return Number.isFinite(n);});return orders.length?Math.max.apply(null,orders)+10:10;}
function p10ComputeDay_(date,rows){const dates=rows.map(function(r){return r.date;}).filter(Boolean).sort(),first=dates[0]||date;return Math.round((new Date(date+'T00:00:00Z')-new Date(first+'T00:00:00Z'))/86400000)+1;}
function p10RequiredDate_(v,l){v=String(v||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(v))throw new Error(l+'格式必須為 YYYY-MM-DD');return v;}
function p10OptionalDate_(v,l){v=String(v||'').trim();return v?p10RequiredDate_(v,l):'';}
function p10OptionalTime_(v,l){v=String(v||'').trim();if(v&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))throw new Error(l+'格式必須為 HH:mm');return v;}
function p10EnumValue_(v,a,l){v=String(v||'').trim();if(!a.includes(v))throw new Error(l+' 值無效');return v;}
function p10RequiredText_(v,l,max){v=String(v||'').trim();if(!v)throw new Error(l+'不可空白');if(v.length>max)throw new Error(l+'過長');return v;}
function p10Text_(v,max){return String(v||'').trim().slice(0,max);}
function p10PositiveNumber_(v,l){const n=Number(v);if(!Number.isFinite(n)||n<0)throw new Error(l+' 必須是 0 以上數字');return n;}
function p10OptionalNumber_(v,l){v=String(v==null?'':v).trim();return v?p10PositiveNumber_(v,l):'';}
function p10BooleanValue_(v,l){if(v===true||String(v).toLowerCase()==='true')return true;if(v===false||String(v).toLowerCase()==='false')return false;throw new Error(l+' 必須是 true/false');}
function p10OptionalHttpsUrl_(v,l){v=String(v||'').trim();if(v&&!/^https:\/\//i.test(v))throw new Error(l+' 必須使用 https://');return v.slice(0,1000);}
function p10ValueForSheet_(v){return v===null||v===undefined?'':v;}
